//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace The_Utopia
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Person()
        {
            this.Family_Person = new HashSet<Family_Person>();
            this.Relationship = new HashSet<Relationship>();
            this.Relationship1 = new HashSet<Relationship>();
            this.Hobby = new HashSet<Hobby>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public System.DateTime Birthday { get; set; }
        public int Age { get; set; }
        public bool Alive { get; set; }
        public string Height { get; set; }
        public string Weight { get; set; }
        public int EyeColor_Id { get; set; }
        public int HairColor_Id { get; set; }
        public int City_Id { get; set; }
        public int Marriage_Id { get; set; }
        public int Occupation_Id { get; set; }
        public int Gender_Id { get; set; }
    
        public virtual City City { get; set; }
        public virtual Eyes Eyes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Family_Person> Family_Person { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual Hair Hair { get; set; }
        public virtual Jobs Jobs { get; set; }
        public virtual Marriage Marriage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Relationship> Relationship { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Relationship> Relationship1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hobby> Hobby { get; set; }
    }
}
